name: MLOps CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run data processing
      run: |
        python python src/Users/bharathreddy/work/mlops/house-price-predictor/src/data/run_processing.py \   
        --input /Users/bharathreddy/work/mlops/house-price-predictor/data/raw/house_data.csv \
        --output /Users/bharathreddy/work/mlops/house-price-predictor/data/processed/cleaned_house_data.csv 

    - name: Do feature engineering
      run: |
          python python src/features/engineer.py \   
          --input /Users/bharathreddy/work/mlops/house-price-predictor/data/processed/cleaned_house_data.csv \
          --output /Users/bharathreddy/work/mlops/house-price-predictor/data/processed/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl

  
    - name: Train the model
      run: |
        python python src/models/train_model.py \  
        --config configs/model_config.yaml \ 
        --data /Users/bharathreddy/work/mlops/house-price-predictor/data/processed/featured_house_data.csv \
        --models-dir models
        --mlflow-tracking-uri http://localhost:5555 
 